# Generated by Django 3.2.12 on 2024-06-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256, unique=True)),
                ('type', models.CharField(max_length=256)),
                ('volume', models.IntegerField()),
                ('release_date', models.DateField(null=True)),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='manga/')),
                ('status_type', models.CharField(choices=[('Paused', 'On Hold'), ('FINISHED', 'Finished'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='tag.tag')),
            ],
        ),
    ]
