# Generated by Django 3.2.12 on 2024-08-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
    ]
