# Generated by Django 3.2.12 on 2024-07-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_description'),
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='tag',
        ),
        migrations.AddField(
            model_name='manga',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='tag.Tag'),
        ),
    ]
