# Generated by Django 3.2.12 on 2023-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='Status',
        ),
        migrations.AddField(
            model_name='manga',
            name='status_type',
            field=models.TextField(choices=[('On Hold', 'On Hold'), ('Finished', 'Finished'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='COMPLETED', max_length=10),
        ),
        migrations.AlterField(
            model_name='manga',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manga',
            name='releaseData',
            field=models.DateField(null=True),
        ),
    ]
