# Generated by Django 3.2.12 on 2024-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20240713_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/anime-img'),
        ),
    ]
