# Generated by Django 3.2.12 on 2024-08-02 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20240802_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
