# Generated by Django 3.2.12 on 2024-07-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_manga_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='static/anime-background-img'),
        ),
    ]
