# Generated by Django 3.2.12 on 2024-07-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('Author', 'author'), ('Designer', 'Designer'), ('Director', 'director'), ('Creator', 'Creator'), ('Character Designer', 'Character Designer')], default='Author', max_length=30)),
            ],
        ),
    ]
