# Generated by Django 3.2.12 on 2024-07-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='assistente',
            new_name='assistant',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='desenhista',
            new_name='designer',
        ),
    ]
