# Generated by Django 3.2.12 on 2024-07-21 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
    ]
