# Generated by Django 3.2.12 on 2024-07-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20240721_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/staff-image'),
        ),
    ]
