# Generated by Django 3.2.12 on 2023-11-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('anime', '0004_alter_anime_status_type'),
        ('manga', '0002_auto_20231120_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anime', models.ManyToManyField(to='anime.Anime')),
                ('manga', models.ManyToManyField(to='manga.Manga')),
                ('staff', models.ManyToManyField(to='staff.Staff')),
            ],
        ),
    ]
