# Generated by Django 3.2.12 on 2024-06-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('anime', '0001_initial'),
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios', to='anime.anime', verbose_name='Anime')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga', verbose_name='Manga')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Staff')),
            ],
        ),
    ]
