# Generated by Django 3.2.12 on 2024-07-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='nome',
            new_name='name',
        ),
    ]
