# Generated by Django 3.2.12 on 2024-07-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_rename_nome_studio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='manga',
        ),
    ]
