# Generated by Django 3.2.12 on 2024-07-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_auto_20240711_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='staff',
        ),
    ]
