# Generated by Django 3.2.12 on 2024-07-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
