# Generated by Django 3.2.12 on 2023-11-17 14:47

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('release_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[(core.utils.Status['ONHOLD'], 'On Hold'), (core.utils.Status['FINISHED'], 'Finished'), (core.utils.Status['COMPLETED'], 'Completed'), (core.utils.Status['CANCELLED'], 'Cancelled')], default='COMPLETED', max_length=10)),
                ('staff', models.ManyToManyField(to='staff.Staff')),
                ('tag', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
    ]
