# Generated by Django 3.2.12 on 2024-07-25 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title_japanese', models.CharField(max_length=256)),
                ('episodes', models.IntegerField(default=0)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('Source', models.CharField(choices=[('manga', 'manga'), ('Light novel', 'Light novel'), ('Crunchyroll', 'Crunchyroll'), ('Netflix', 'Netflix')], default='default_value', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime-img/')),
                ('Background', models.ImageField(blank=True, null=True, upload_to='anime-background-img/')),
                ('studios', models.ManyToManyField(to='studio.Studio', verbose_name='studios')),
                ('tag', models.ManyToManyField(to='tag.Tag', verbose_name='Tag')),
            ],
        ),
    ]
