# Generated by Django 3.2.12 on 2023-11-20 11:20

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20231117_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status_type',
            field=models.TextField(choices=[(core.utils.Status['ONHOLD'], 'On Hold'), (core.utils.Status['FINISHED'], 'Finished'), (core.utils.Status['COMPLETED'], 'Completed'), (core.utils.Status['CANCELLED'], 'Cancelled')], default='COMPLETED', max_length=10),
        ),
    ]
