# Generated by Django 3.2.12 on 2024-07-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20240712_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='status_type',
        ),
        migrations.AlterField(
            model_name='anime',
            name='Source',
            field=models.CharField(choices=[('manga', 'manga'), ('Night lovel', 'Night lovel'), ('Crunchyroll', 'Crunchyroll'), ('Netflix', 'Netflix')], default='default_value', max_length=100),
        ),
    ]
