# Generated by Django 3.2.12 on 2023-11-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status_type',
            field=models.TextField(choices=[('On Hold', 'On Hold'), ('Finished', 'Finished'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='COMPLETED', max_length=10),
        ),
    ]
