# Generated by Django 3.2.12 on 2024-08-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
        ('manga', '0001_initial'),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='anime'),
        ),
        migrations.AlterField(
            model_name='character',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.manga', verbose_name='manga'),
        ),
    ]
