# Generated by Django 3.2.12 on 2024-07-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile-img/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
