# Generated by Django 3.2.12 on 2024-07-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewanime',
            old_name='manga',
            new_name='anime',
        ),
    ]
