# Generated by Django 3.2.12 on 2024-07-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_auto_20240713_0314'),
        ('user', '0002_rename_manga_reviewanime_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanime',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
    ]
