# Generated by Django 3.2.12 on 2024-07-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animestate',
            old_name='Progress',
            new_name='progress',
        ),
    ]
