# Generated by Django 3.2.12 on 2024-08-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_progress_animestate_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangastate',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='mangastate',
            name='user',
        ),
        migrations.RenameField(
            model_name='reviewanime',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='reviewmanga',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manga',
        ),
        migrations.AddField(
            model_name='user',
            name='anime_states',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='manga_states',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='AnimeState',
        ),
        migrations.DeleteModel(
            name='MangaState',
        ),
    ]
